version: '3.8'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,lambda,logs
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      #- LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=300
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=false
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/var/lib/localstack"
